language: scala
sudo: false
script: sbt "++ 2.12.2" "^^ 1.0.0-RC2" scripted
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
addons:
  apt:
    packages:
    - oracle-java8-installer
